# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt_files\LogIn.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(302, 289)
        Dialog.setStyleSheet("#groupBox{\n"
"    Background-color: #f2f3f4;\n"
"}")
        self.login_ok = QtWidgets.QPushButton(Dialog)
        self.login_ok.setGeometry(QtCore.QRect(50, 230, 75, 23))
        self.login_ok.setObjectName("login_ok")
        self.login_cancel = QtWidgets.QPushButton(Dialog)
        self.login_cancel.setGeometry(QtCore.QRect(160, 230, 75, 23))
        self.login_cancel.setObjectName("login_cancel")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 30, 241, 181))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(40, 30, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.login_user = QtWidgets.QLineEdit(self.groupBox)
        self.login_user.setGeometry(QtCore.QRect(30, 60, 191, 31))
        self.login_user.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.login_user.setObjectName("login_user")
        self.login_pass = QtWidgets.QLineEdit(self.groupBox)
        self.login_pass.setGeometry(QtCore.QRect(30, 130, 191, 31))
        self.login_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.login_pass.setObjectName("login_pass")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Back End Log-In"))
        self.login_ok.setText(_translate("Dialog", "Ok"))
        self.login_cancel.setText(_translate("Dialog", "Cancel"))
        self.groupBox.setTitle(_translate("Dialog", "Log in"))
        self.label_2.setText(_translate("Dialog", "Password"))
        self.label.setText(_translate("Dialog", "Username"))
